

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql:///postgres
    username: postgres
    password: 12345678

    hikari:
      data-source-properties:
        socketFactory: com.google.cloud.sql.postgres.SocketFactory
        cloudSqlInstance: recipe-app-demo-374220:europe-west3:demodb

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


