server:
  port: 8080


spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql:///${DB_DATABASE:postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:12345678}

    hikari:
      minimum-idle: 2
      maximum-pool-size: 5
      data-source-properties:
        socketFactory: com.google.cloud.sql.postgres.SocketFactory
        cloudSqlInstance: ${CLOUD_SQL_INSTANCE}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


