spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/recipes
    username: postgres
    password: postgres

    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
    show-sql: true