

spring:
  config:
    import: optional:oauth.yaml
  profiles:
    active: prod
  security:
    oauth2:
      # noinspection SpellCheckingInspection
      resourceserver:
        jwt:
          jwk-set-uri: https://www.googleapis.com/service_accounts/v1/jwk/securetoken%40system.gserviceaccount.com
          issuer-uri: https://securetoken.google.com/kit-recipe-app


